PATH_OUT_DIR: C:\\CODE\\py_neuromodulation\\realtime_experiment\\data
PATH_XML_CONFIG: C:\\CODE\\py_neuromodulation\\realtime_experiment\\saga_config_sensight_lfp_left.xml

PATH_MODEL_PREDICT: C:\\CODE\\py_neuromodulation\\realtime_experiment\\model_STN_best_ch_all_sub_ALL.p
PATH_pynm_SETTINGS: C:\\CODE\\py_neuromodulation\\realtime_experiment\\nm_settings_feat.json
PATH_pynm_CHANNELS: C:\\CODE\\py_neuromodulation\\realtime_experiment\\nm_channels_feat.csv

sub: testsub
task: rotameter
ses: EcogLfpMedOff01
acq: StimOff
datatype: ieeg
run:  1
