PATH_OUT_DIR: C:\\code\\py_neuromodulation\\realtime_experiment\\data
PATH_XML_CONFIG: C:\\code\\py_neuromodulation\\realtime_experiment\\saga_confif_sensight_ecog.xml

PATH_MODEL_PREDICT: C:\\code\\py_neuromodulation\\realtime_experiment\\trained_model_STN_best_ch.p
PATH_pynm_SETTINGS: C:\\code\\py_neuromodulation\\realtime_experiment\\nm_settings_feat.json
PATH_pynm_CHANNELS: C:\\code\\py_neuromodulation\\realtime_experiment\\nm_channels_feat.csv

sub: testsub
task: rotameter
ses: EcogLfpMedOff01
acq: StimOff
datatype: ieeg
run:  1
