[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools"]

[project]
authors = [{name = "Richard M. Köhler"}]
classifiers = [
  "Development Status :: 2 - Pre-Alpha",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
  "EDFlib-python",
  "matplotlib",
  "mne",
  "numpy",
  "pandas",
  "Pillow",
  "pylsl",
  "pyqtgraph",
  "PySide2",
  "pyxdf",
]
description = "tmsi is a package derived from TMSi's python interface."
keywords = ["tmsi", "eeg", "ieeg"]
license = {file = "LICENSE"}
maintainers = [{name = "Richard M. Köhler"}]
name = "tmsi"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.10"
version = "0.1.0"
