name: pn_env
channels:
  - conda-forge  
dependencies:
  - python>=3.10
  - mne
  - mne-connectivity
  - mne-bids>=0.9
  - numpy=1.21
  - pandas
  - scikit-learn
  - scipy
  - ipykernel
  - pytest
  - filterpy
  - fooof
  - scikit-optimize
  - xgboost
  - imbalanced-learn
  - pip
  - pip:
      - mrmr_selection
      - nolds
      - pybids>=0.12.4
