name: docs_pages_workflow
 
on:
  push:
    branches: [ main ]
 
jobs:
 
  build_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
 
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Set up Python with uv
        uses: drivendataorg/setup-python-uv-action@v1
        with:
          python-version: ${{ matrix.python }}
          cache: packages
          cache-dependency-path: pyproject.toml
 
      - name: Install dependencies
        run: |
          uv pip install .[test]

      - name: make the sphinx docs
        run: |
          make -C docs clean 
          make -C docs html

      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "merkimi1996@googlemail.com"
          git config --local user.name "timonmerk"
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/build/html
