name: Tests
on:
  push:
    branches:
      - main
      - '**'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.txt'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.txt'
jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    env:
      APPDATA: DefaultNonExistingPath 
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: 3.10 Mac, python: '3.10', os: macos-latest, tox: py310}
          - {name: 3.10 Linux, python: '3.10', os: ubuntu-latest, tox: py310}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: update pip
        run: |
          python -m pip install -U pip
      - name: get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: cache pip
        uses: actions/cache@v3
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('requirements/*.txt') }}
          restore-keys: pip|${{ runner.os }}|${{ matrix.python }}
      - name: Install liblsl (linux)
        if: ${{ matrix.os == 'ubuntu' }}
        run: |
          curl -L https://github.com/sccn/liblsl/releases/download/v1.16.2/liblsl-1.16.2-jammy_amd64.deb -o liblsl-1.16.2-jammy_amd64.deb
          sudo apt update
          sudo apt install -y binutils libpugixml-dev qtbase5-dev qt5-qmake
          sudo apt install -y ./liblsl-1.16.2-jammy_amd64.deb
          rm liblsl-1.16.2-jammy_amd64.deb
      - name: Install dependencies
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip install --progress-bar off .[test]
      - run: pip install tox
        env:
          APPDATA: DefaultNonExistingPath 
      - run: tox -e ${{ matrix.tox }}
