name: Tests
on:
  push:
    branches:
      - main
      - '**'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.txt'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.txt'
jobs:
  tests:
    name: ${{ matrix.platform.name }} Python ${{ matrix.python }}
    runs-on: ${{ matrix.platform.os }}
    env:
      MNE_LSL_LIB: ${{ github.workspace }}/liblsl.1.16.0.dylib
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            name: Linux
          - os: macos-latest
            name: MacOS
          - os: windows-latest
            name: Windows
        python:
          - '3.10'
    steps:
      - uses: actions/checkout@v4
      - name: Install liblsl (linux)
        if: ${{ matrix.platform.name == 'Linux' }}
        run: |
          curl -L https://github.com/sccn/liblsl/releases/download/v1.16.2/liblsl-1.16.2-jammy_amd64.deb -o liblsl-1.16.2-jammy_amd64.deb
          sudo apt update
          sudo apt install -y binutils libpugixml-dev qtbase5-dev qt5-qmake ./liblsl-1.16.2-jammy_amd64.deb
          rm liblsl-1.16.2-jammy_amd64.deb
      - name: Set up Python with uv
        uses: drivendataorg/setup-python-uv-action@v1
        with:
          python-version: ${{ matrix.python }}
          cache: packages
          cache-dependency-path: pyproject.toml
      - name: Install dependencies
        run: uv pip install -q .
      - name: Install pytest
        run: uv pip install -q pytest pytest-xdist pytest-sugar
      - name: Run tests
        run: pytest -n auto tests/
