name: Tests
on:
  push:
    branches:
      - main
      - '**'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.txt'
  pull_request:
    branches:
      - main
      - '*.x'
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - '*.rst'
      - '*.txt'
jobs:
  tests:
    name: ${{ matrix.platform.name }} Python ${{ matrix.python }}
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: ubuntu-latest
            name: Linux
          - os: macos-latest
            name: MacOS
          - os: windows-latest
            name: Windows
        python:
          - '3.10'
    steps:
      - uses: actions/checkout@v4
      - name: Install and cache Linux packages
        if: ${{ runner.os == 'Linux' }}
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: binutils qtbase5-dev qt5-qmake libpugixml1v5 xvfb
      - name: Set up Python with uv
        uses: drivendataorg/setup-python-uv-action@v1
        with:
          python-version: ${{ matrix.python }}
          cache: packages
          cache-dependency-path: pyproject.toml
      - name: Install test dependencies
        run: uv pip install .[test]
      - name: Run tests
        run: ${{ runner.os == 'Linux' && 'xvfb-run' || '' }} pytest -n auto tests/
